ci: switch Fedora registry locations
I had thought registry.fedoraproject.org was preferable for their
images, but with rawhide (not latest) pulls we're seeing:

Trying to pull registry.fedoraproject.org/fedora:rawhide...
Error: choosing an image from manifest list
docker://registry.fedoraproject.org/fedora:rawhide: no image found in
manifest list for architecture amd64, variant "", OS linux

And it's happening for me locally too. Switch to docker.io.

Signed-off-by: Nathan Lynch <nathanl@linux.ibm.com>
Signed-off-by: Tyrel Datwyler <tyreld@linux.ibm.com>